# 2.0 协议可以是tcp udp

gateway:
  port: 4321
  protocol: tiza2.0
  socketprotocol: udp
  socket:
    host: 58.218.151.98
    port: 4321

forward:
  gateway:
    host: 192.168.1.121
    port: 7120

    #host: 192.168.1.152
    #port: 7120
    #host: 192.168.1.121
    #port: 7120